// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkxh92sjdeOgATNUigkkjDtzWm0Xw9v0',
    appId: '1:853002897607:web:8e93d60f9b28f8325dd6e2',
    messagingSenderId: '853002897607',
    projectId: 'routineranger',
    authDomain: 'routineranger.firebaseapp.com',
    storageBucket: 'routineranger.firebasestorage.app',
    measurementId: 'G-HLN0SB520L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4a6WWhSvkfwIAVkXOyCZ_ZjXxSRLi-Ec',
    appId: '1:853002897607:android:01394583f54d6e4a5dd6e2',
    messagingSenderId: '853002897607',
    projectId: 'routineranger',
    storageBucket: 'routineranger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1pinzxZcxpQobjpeQ226L3fvea6nHabs',
    appId: '1:853002897607:ios:4c7dff931b81ba405dd6e2',
    messagingSenderId: '853002897607',
    projectId: 'routineranger',
    storageBucket: 'routineranger.firebasestorage.app',
    iosBundleId: 'com.example.ranger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1pinzxZcxpQobjpeQ226L3fvea6nHabs',
    appId: '1:853002897607:ios:4c7dff931b81ba405dd6e2',
    messagingSenderId: '853002897607',
    projectId: 'routineranger',
    storageBucket: 'routineranger.firebasestorage.app',
    iosBundleId: 'com.example.ranger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpkxh92sjdeOgATNUigkkjDtzWm0Xw9v0',
    appId: '1:853002897607:web:8e93d60f9b28f8325dd6e2',
    messagingSenderId: '853002897607',
    projectId: 'routineranger',
    authDomain: 'routineranger.firebaseapp.com',
    storageBucket: 'routineranger.firebasestorage.app',
    measurementId: 'G-HLN0SB520L',
  );
}
