const List<String> motivationalQuotes = [
  "Success is the sum of small efforts repeated day in and day out.",
  "You don't have to be great to start, but you have to start to be great.",
  "The secret of getting ahead is getting started.",
  "Don't watch the clock; do what it does. Keep going.",
  "The only way to do great work is to love what you do.",
  "Your future is created by what you do today, not tomorrow.",
  "Small daily improvements lead to stunning results.",
  "Consistency is the key to success.",
  "Every accomplishment starts with the decision to try.",
  "The difference between ordinary and extraordinary is that little extra.",
  "You are what you repeatedly do. Excellence is not an act, but a habit.",
  "Believe you can and you're halfway there.",
  "Start where you are. Use what you have. Do what you can.",
  "The only impossible journey is the one you never begin.",
  "Don't count the days, make the days count.",
  "A journey of a thousand miles begins with a single step.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Success doesn't come from what you do occasionally. It comes from what you do consistently.",
  "Dream big, start small, act now.",
];
